language: go

before_install:
  - go get github.com/mattn/goveralls

script:
  - go test -v -cover -coverprofile coverage.out ./parser/
  - $HOME/gopath/bin/goveralls -coverprofile coverage.out -service=travis-ci
